version: "3.9"

services:
  app:
    container_name: garageRemote
    image: garage-remote
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4321:4321"
      - "8080:80"
